---
title: 'Career path in Research software Community in United-Kingdom'
author: "Olivier PHILIPPE"
date: "26 June 2016"
output:
    html_document:
        keep_md: yes
        number_sections: yes
        toc_depth: 4
    github_document:
        md_extensions: -autolink_bare_uris+hard_line_breaks
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
    # Setting up the directory
    ## Work only on linux -- if it is not working needs to insert manually
    this.dir = system("pwd", intern = T) 
    setwd(this.dir)
    setwd('~/git/ssi/RSE-Survey-2016/')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
    knitr::read_chunk('/home/olivier/git/ssi/RSE-Survey-2016/R/Influence of work.R')
```

```{r loadFile, echo=FALSE, message=FALSE, warning=FALSE}
```

```{r sourceFunc, echo=FALSE, message=FALSE, warning=FALSE}
```

```{r loadLibrary, echo=FALSE, message=FALSE, warning=FALSE}
```


# Introduction

One problematic inherent to any emergence of a new role within well establish structure (here the university), it is the difficulty to have a clear career path for the people that are coming to fill that new role. 
This problem directly hits the community of Research Software Engineers in United-Kingdom.



```{r tableAcademy}
```