---
title: "RSE Survey 2016"
author: "Olivier PHILIPPE"
date: "26 June 2016"
output:
  html_document:
    keep_md: yes
    number_sections: yes
    toc_depth: 4
  github_document:
    md_extensions: -autolink_bare_uris+hard_line_breaks
  pdf_document:
    toc_depth: '4'
---

```{r package_options, include=FALSE}
    # Specfy the output format
    options(knitr.table.format = 'markdown')
    # Specify global option for the figures
    knitr::opts_chunk$set(fig.width = 20, fig.height = 15)
    knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, dev=c('png', 'svg', 'pdf'))
```

```{r}
    # Setting up the directory
    ## Work only on linux -- if it is not working needs to insert manually
    this.dir = system("pwd", intern = T) 
    setwd(this.dir)
    setwd('~/git/ssi/RSE-Survey-2016/')
```

```{r}
    knitr::read_chunk('/home/olivier/git/ssi/RSE-Survey-2016/R/univariate_analysis.R')
```

```{r sourceFunc}
```

```{r loadLibs}
```

```{r loadFile}
```

```{r disciplinePrep}
```

```{r disciplineTable}
```

```{r disciplinePlot, fig.width=20, fig.height=20}
```

```{r educationPrep}
```


```{r educationTable}
```

```{r educationPlot}
```

```{r genderPrep}
```

```{r genderTable}
```

```{r genderPlot}
```

```{r genderAllPrep}
```

```{r genderAllPlot}
```

```{r contractPrep}
```

```{r contractTable}
```

```{r contractPlot}
```


```{r salaryPrep}
```

```{r salarayTable}
```

```{r salaryPlot}
```

```{r salaryAllPrep}
```

```{r salaryAllPlot}
```

```{r busFactorPrep}
```

```{r busFactorTable}
```

```{r busFactorPlot}
```

```{r handOverPrep}
```

```{r handOverTable}
```

```{r handOverPlot}
```

```{r contribYNPrep}
```

```{r contribYNTable}
```

```{r contribYNPlot}
```

```{r contribAllPrep}
```

```{r contribAllPlot}
```

```{r workIndicatorPrep}
```

```{r workIndicatorPlot}
```

```{r careerPrep}
```

```{r careerPlot}
```

```{r skillImportantPrep}
```

```{r skillImportantPlot, fig.width=30, fig.height=20}
```

```{r skillImprovePrep}
```

```{r skillImprovePlot, fig.width=30, fig.height=30}
```

```{r toolPrep}
```

```{r toolPlot, fig.width=20, fig.height=20}
```
