---
title: 'RSE Survey 2016'
author: "Olivier PHILIPPE"
date: "26 June 2016"
output:
    html_document:
        keep_md: yes
        number_sections: yes
        toc_depth: 4
    github_document:
        md_extensions: -autolink_bare_uris+hard_line_breaks
---

```{r package_options, include=FALSE}
    # Specfy the output format
    options(knitr.table.format = 'markdown')
```

```{r echo=FALSE}
    # Setting up the directory
    ## Work only on linux -- if it is not working needs to insert manually
    this.dir = system("pwd", intern = T) 
    setwd(this.dir)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
    # Source the functions.R file
    source('./R/functions.R')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
    # Load all the libraries
    library('rmarkdown')
    library('knitr')
    library('ggplot2')
    library('stringr')  # To wrap the too long labels in the plots
    library('psy')
    library('reshape2')
    library('dplyr')
```


```{r echo=FALSE}
    ## LOAD FILE
    df <- read.csv('./data/592_full_clean.csv',  na.strings=c("NA","NaN", " ", ""))
```


# Socio-demographic information
## Disciplines

```{r fig.width=20, fig.height=10, echo=FALSE}
    sumQ <- singleTabFreq(df$Edu.academic.CLEAN, 'Field of Education')
    kable(sumQ, digits=2, format = 'markdown')
    plotSingleFreq(sumQ, 'Field of Education', column= 'Percent', vertical_label=TRUE)
    # png('/figs/education_field.png', width=1400, height=1000)
    # p
    # dev.off()
```

## Level of education
```{r echo=FALSE}
    # Reorder the factor
    levels(df$Edu.highest_qualification) <- c('Doctorate', 'Undergraduate/Others', 'Master Degree', 
                                              'Undergraduate/Others', 'Undergraduate/Others',
                                              'Undergraduate/Others', 'Undergraduate/Others')
    df$Edu.highest_qualification = factor(df$Edu.highest_qualification, levels(df$Edu.highest_qualification)[c(1,3,2)])
```

```{r fig.width=20, fig.height=10, echo=FALSE}

    sumQ <- singleTabFreq(df$Edu.highest_qualification, 'level of Education')
    kable(sumQ, digits=2, format = 'markdown')
    p <- plotSingleFreq(sumQ, 'Level of Education', column='Percent')
    p 
    # png('plots/education_level.png', width=1400, height=1000)
    # p
    # dev.off()
```

## Salary
```{r echo=FALSE}
    # Reorder factors
    df$Socio.salary = factor(df$Socio.salary, levels(df$Socio.salary)[c(10,9,1:8)])
```

```{r fig.width=20, fig.height=10, echo=FALSE}
    # Plot
    sumQSalary <- singleTabFreq(df$Socio.salary, 'Salary', order=FALSE)
    kable(sumQSalary, digits=2, format = 'markdown')
    p <- plotSingleFreq(sumQSalary, 'Salary', order=FALSE)
    p
    # png('plots/salary.png', width=1400, height=1000)
    # p
    # dev.off()
```

### Comparison with the salary for academic staff in UK

```{r echo=FALSE}
    # salaryDf <- read.xls('./data/staff_1415_table_B.xlsx', sheet='Table_B', header=True)
    salaryRaw <- read.csv('./data/staff_1415_table_B.csv')
    ## Subset only the total of salary for all and the associated percentage
    salaryDf <- salaryRaw[c(16,17,18,19,20,21), c(1, 20,21)]
    ## Rename the columns
    colnames(salaryDf) <- c('Salary', 'Total Respondends', 'Percent')
    ## Rename the range of salary to match the salary obtained in the RSE survey
    ## The range are different and an approximation is made to get the closest similarity between the two
    ## surveys. The comparison needs to be carefully interpreted as the ranges are overlapping and are not cuttin
    ## at the same salary
    salaryDf$Salary <- as.factor(as.character(salaryDf$Salary))
    levels(salaryDf$Salary) <- c('Under £25,000', 'Under £25,000', '>= £25,000 and < £34,000', '>= £34,000 and < £45,000', '>= £45,000 and < £59,000', '>= £59,000')
    ## Rename the Percent value to remove the percent and transform into number
    salaryDf$Percent <- as.numeric(as.character(gsub('%', '',salaryDf$Percent)))
    ### Sum the multiple categories created by the recategorisation
    percent_All_UK <- as.data.frame(salaryDf %>%
                                        group_by(Salary) %>%
                                        summarise(Percent = sum(Percent)))
    ## Reorganise the salary from the RSE survey to match the new created categories
    levels(sumQSalary$Salary) <- c('Under £25,000', '>= £59,000', '>= £59,000',  '>= £25,000 and < £34,000',  '>= £25,000 and < £34,000', 
                                   '>= £34,000 and < £45,000', '>= £34,000 and < £45,000', '>= £45,000 and < £59,000', '>= £45,000 and < £59,000',
                                   '>= £59,000')
    ### Sum the multiple categories created by the recategorisation
    percent_RSE <- as.data.frame(sumQSalary %>%
                                        group_by(Salary) %>%
                                        summarise(Percent = sum(Percent)))
    ### Reorder factors
    percent_RSE$Salary <- factor(percent_RSE$Salary, levels(percent_RSE$Salary)[c(1,3,4,5,2)])
```


```{r fig.width=20, fig.height=10, echo=FALSE}

    p <-    ggplot(data=percent_RSE, aes(x=Salary, y=Percent, fill=Salary))+
            # geom_bar(stat='identity', position=position_dodge())+
            geom_bar(stat='identity', show.legend = FALSE)+
            geom_line(data=percent_All_UK, aes(x=Salary, y=Percent, group='factor'), colour="blue")+
            geom_point(data=percent_All_UK, aes(x=Salary, y=Percent, group='factor'), colour="blue")+
            geom_text(data=percent_All_UK, aes(label=paste(Percent, '%')),  vjust=-0.2, size=6, colour='blue')+
            geom_text(aes(label=paste(Percent, '%')),  vjust=-0.2, size=6)+
            scale_color_brewer(palette='Paired')+
            theme_minimal()+
            ylab('Percentages')+
            xlab('')+
            ggtitle('Comparison Salary between RSE and UK academic staff')+
            theme(plot.title = element_text(size=30, face='bold'))+
            theme(legend.position='none')+
            # theme(legend.text=element_text(size=20))+
            # theme(legend.title=element_blank())+
            theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
    p
```


## Gender

```{r echo=FALSE}
    # Gender in IT -- Data from: https://docs.google.com/spreadsheets/d/1nr2ukhV2rNInLTR210yBKEvJowU9vfg6rkckFoi_1Io/edit#gid=349336051
    # Gender in RSE
    sumQ <- singleTabFreq(df$Socio.gender, 'Gender', order=TRUE)
    sumQ$Discipline <- c('RSE', 'RSE')
    # Gender in IT -- Data from: https://docs.google.com/spreadsheets/d/1nr2ukhV2rNInLTR210yBKEvJowU9vfg6rkckFoi_1Io/edit#gid=349336051
    genderDf <- read.csv('data/gender_disciplines.csv')
    genderDf$Discipline <- as.character(genderDf$Discipline)
    ## TODO -- FIX THAT NOT DOING IT MANUALLY WRONG
    genderDf <- rbind(genderDf, c('RSE', '12', '88'))
    genderDf$Discipline <- as.factor(genderDf$Discipline)
    genderDf <- melt(genderDf, c('Discipline'))
    genderDf$value <- as.numeric(genderDf$value)
```


```{r fig.width=20, fig.height=10, echo=FALSE}
    kable(sumQ, digits=2, format = 'markdown')
    p <-    ggplot(data=genderDf[genderDf$variable =='Female',], aes(x=reorder(Discipline, value), y=value))+
            # geom_bar(stat='identity', position=position_dodge())+
            geom_bar(stat='identity', show.legend = FALSE, fill='#4A8F94', colour='#4A8F94')+
            #geom_bar(stat='identity') +
            #scale_color_brewer(palette='#4A8F94')+
            theme_minimal()+
            ylab('Percentage')+
            xlab('')+
            ggtitle('Gender in CS and RSE')+
            theme(plot.title = element_text(size=30, face='bold'))+
            theme(legend.position='none')+
            theme(legend.text=element_text(size=20))+
            theme(legend.title=element_blank())+
            theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+
            #geom_text(aes(label=mergedDF$Gender), vjust=-0.2, size=8)+
            geom_text(aes(label=paste(value, '%')),  vjust=-0.2, size=4)
    p
    # png('plots/gender.png', width=1400, height=1000)
    # p
    # dev.off()
```

# Good practices

## Bus Factor

```{r fig.width=20, fig.height=10, echo=FALSE}
    sumQ <- singleTabFreq(df$Stability.bus_factor, 'Bus Factor', order=FALSE)
    kable(sumQ, digits=2, format = 'markdown')
    p <- plotSingleFreq(sumQ, 'Bus Factor', column = 'Percent', order=FALSE)
    p
    # png('plots/stability_bus-factor.png', width=1400, height=1000)
    # p
    # dev.off()
```

## Technical hand over

```{r fig.width=20, fig.height=10, echo=FALSE}
  # Plot
    sumQ <- singleTabFreq(df$Stability.hand_over, 'Technical hand over', order=TRUE)
    kable(sumQ, digits=2, format = 'markdown')
    p <- plotSingleFreq(sumQ, 'Technical hand over', column = 'Percent', order=TRUE)
    p
    # png('plots/stability_hand-over.png', width=1400, height=1000)
    # p
    # dev.off()
```


## Contribution papers

```{r fig.width=20, fig.height=10, echo=FALSE}
    sumQ <- singleTabFreq(df$Contrib.YN, 'Contribution to paper')
    kable(sumQ, digits=2, format = 'markdown')
    p <- plotSingleFreq(sumQ, 'Contribution to paper', column = 'Percent', order=TRUE)
    p    
    # png('plots/contribution_paper.png', width=1400, height=1000)
    # p 
    # dev.off()
```


## Indicators

```{r echo=FALSE}
    ## Create df
    dfIndicators <- data.frame('Turnover intention'=df$TurnOver.Agg, 'Perceived Employability'=df$PercEmp.Agg,
                               'Satisfaction'=df$AffSat.Agg, 'Recognition'=df$AffRec.Agg,
                               'Feedback'= df$PerfCheck.Agg)

    dfIndicators <- melt(dfIndicators)
```

```{r fig.width=20, fig.height=10, echo=FALSE}
    p <- ggplot(dfIndicators, aes(x=variable, y=value, color=variable))+
         geom_boxplot(show.legend=FALSE)+
         geom_jitter(alpha=0.25, color='Grey')+
         scale_color_brewer(palette='Paired') +
         theme_minimal() +
         ylab('Mean of Aggregate score') +
         xlab('') +
         ggtitle('Work Indicators') +
         theme(plot.title = element_text(size=30, face='bold')) +
         theme(legend.text=element_text(size=20)) +
         theme(legend.title=element_blank())
    p
    # png('plots/indicators.png')
    # p
    # dev.off()
```

## Contribution to papers
```{r echo=FALSE, warning=FALSE}
    ## FIXME -- DONE IN A RUSH AND EVEN MANUALLY ENTER THE %. NEED TO REDO ALL THIS BIT
    dfContrib <- data.frame('Contribution'=df$Contrib.YN, 'Acknowledged'=df$Contrib.acknowledgedYN,
                            'Co-author'=df$Contrib.co.authorYN, 'Lead-author'=df$Contrib.leadYN)
    levels(dfContrib$Contribution) <- c(NA, 'No', 'Yes')
    # summary(dfContrib$Contribution)
    # sd(na.omit(dfContrib$Contribution))
    
    levels(dfContrib$Acknowledged) <- c(NA, 'No', 'Yes')
    # summary(na.omit(dfContrib$Acknowledged))
    levels(dfContrib$Co.author) <- c(NA, 'No', 'Yes')
    # sd(na.omit(dfContrib$Co.author))
    levels(dfContrib$Lead.author) <- c(NA, 'No', 'Yes')
    # summary(dfContrib$Lead.author)
    # sd(na.omit(dfContrib$Lead.author))
    dfContribMelt <- melt(dfContrib)
    sumQ <- singleTabFreq(df$Contrib.YN, 'Contribution to paper')
    sumQ$Participation <- 'Contribution to paper' 
    df1 <- as.data.frame(summary(na.omit(dfContrib$Contribution)))
    df2 <- as.data.frame(summary(na.omit(dfContrib$Acknowledged)))
    df3 <- as.data.frame(summary(na.omit(dfContrib$Co.author)))
    df4 <- as.data.frame(summary(na.omit(dfContrib$Lead.author)))
    dfTest <- merge(df1, df2)
    dfTest <- merge(dfTest, df3)
    dfTest <- merge(dfTest, df4)
    dfTest <- dfTest[c(1, 16),]
    rownames(dfTest) <- c('No', 'Yes')
    colnames(dfTest) <- c('1.Contribution', '2.Acknowledged', '3.Co-author', '4.Lead-author')
    dfTestMelt <- as.data.frame(t(dfTest))
    dfTestMelt$Paper <- rownames(dfTestMelt)
    dfTestMelt <- melt(dfTestMelt)
    dfTestMelt$Percent <- c((27/(27+230))*100, 
                          (55/(55+174))*100,
                          (72/(72+158))*100,
                          (139/(139+91))*100,
                          (230/(230+27))*100,
                          (174/(174+55))*100,
                          (158/(158+72))*100,
                          (91/(91+139))*100)
    
    colnames(dfTestMelt) <- c('Participation', 'Answer', 'value', 'Percent')
```


```{r fig.width=20, fig.height=10, echo=FALSE}
    ggplot(dfTestMelt, aes(Participation, y=Percent, fill=Answer))+
        geom_bar(stat='identity', position=position_dodge(width=1)) +
        geom_text(aes(label=paste(round(Percent), '%')), size=8,vjust=-0.2, position=position_dodge(width = 1))+
        ggtitle('Contribution to Papers')+
        theme_minimal() +
        scale_fill_brewer(palette='Paired')+
        theme(legend.text=element_text(size=15)) +
        theme(legend.title=element_blank())
```


# Word cloud

## Important skills

```{r echo=FALSE}
    ### Most important skills
    skill1_important <- df$Misc.skill.imp.1
    skill2_important <- df$Misc.skill.imp.2
    skill3_important <- df$Misc.skill.imp.3
    skills_important <- c(as.character(skill1_important),
                          as.character(skill2_important),
                          as.character(skill3_important))
    wordToRemove <- c('skills', 'ability', 'skill')
    skills_important <- cleanText(skills_important, wordToRemove = wordToRemove)
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
    p <- wordcloud(skills_important, random.color=FALSE, colors=brewer.pal(8, "Paired"))
    p
  # png('plots/wordcloud_skill_important.png')
  # p
  # dev.off()
```


### Skills to improve

```{r echo=FALSE}
  skills1_to_improve <- df$Misc.skill.better.1
  skills2_to_improve <- df$Misc.skill.better.2
  skills3_to_improve <- df$Misc.skill.better.3
  skills_improve <- c(as.character(skills1_to_improve),
                      as.character(skills2_to_improve),
                      as.character(skills3_to_improve))
  skills_improve <- cleanText(skills_improve, wordToRemove = wordToRemove)
  wordToRemove <- c('skill', 'skills', 'better', 'improve')
```
 
```{r echo=FALSE, warning=FALSE, message=FALSE}
  p <- wordcloud(skills_improve, random.color=FALSE, colors=brewer.pal(8, "RdYlGn"))
  p
  # png('plots/wordcloud_skill_improve.png')
  # p
  # dev.off()
```

### Tools used

```{r echo=FALSE, message=FALSE, warning=FALSE}
  tool1 <- df$Misc.tool.1
  tool2 <- df$Misc.tool.2
  tool3 <- df$Misc.tool.3
  all_tools <- c(as.character(tool1),
                 as.character(tool2),
                 as.character(tool3))

  all_tools <- cleanText(all_tools, wordToRemove = c('tools', 'system'))
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
    p <- wordcloud(all_tools, random.color=FALSE, colors=brewer.pal(8, "RdYlGn"))
    p
    # png('plots/wordcloud_tools.png')
    # p
    # dev.off()
```